#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck disable=SC1091
. "$ROOT/deploy/cloud-vps/lib.sh"

output_path="${1:-${WIKI_ECON_ENV_FILE:-/etc/wiki-economics.env}}"
output_dir="$(dirname "$output_path")"
tmp_path=""

cleanup() {
  if [ -n "$tmp_path" ] && [ -f "$tmp_path" ]; then
    rm -f "$tmp_path"
  fi
}
trap cleanup EXIT

: "${WIKI_ECON_ENV:=production}"
: "${WIKI_ECON_REPO_URL:=https://github.com/schiste/wiki-economics.git}"
: "${WIKI_ECON_REPO_REF:=main}"
: "${WIKI_ECON_APP_ROOT:=/srv/wiki-economics/app}"
: "${WIKI_ECON_APP_RELEASES:=$WIKI_ECON_APP_ROOT/releases}"
: "${WIKI_ECON_APP_CURRENT:=$WIKI_ECON_APP_ROOT/current}"
: "${WIKI_ECON_DATA_DIR:=/srv/wiki-economics/data}"
: "${WIKI_ECON_OUTPUT_ROOT:=/srv/wiki-economics/output}"
: "${WIKI_ECON_OUTPUT_RELEASES:=$WIKI_ECON_OUTPUT_ROOT/releases}"
: "${WIKI_ECON_OUTPUT_CURRENT:=$WIKI_ECON_OUTPUT_ROOT/current}"
: "${WIKI_ECON_SITE_ROOT:=/srv/wiki-economics/site}"
: "${WIKI_ECON_SITE_RELEASES:=$WIKI_ECON_SITE_ROOT/releases}"
: "${WIKI_ECON_SITE_CURRENT:=$WIKI_ECON_SITE_ROOT/current}"
: "${WIKI_ECON_SITE_DIST_DIR:=$WIKI_ECON_SITE_CURRENT}"
: "${WIKI_ECON_STATE_ROOT:=/srv/wiki-economics/state}"
: "${WIKI_ECON_ENABLED_WIKIS_FILE:=/etc/wiki-economics/wikis.txt}"
: "${WIKI_ECON_SERVICE_USER:=wiki-econ}"
: "${WIKI_ECON_ADMIN_ENABLED:=1}"
: "${WIKI_ECON_ADMIN_AUTH_MODE:=oidc}"
: "${WIKI_ECON_ADMIN_PORT:=3001}"
: "${WIKI_ECON_ADMIN_PUBLIC_ORIGIN:=}"
: "${WIKI_ECON_ADMIN_OIDC_ISSUER:=}"
: "${WIKI_ECON_ADMIN_OIDC_CLIENT_ID:=}"
: "${WIKI_ECON_ADMIN_OIDC_CLIENT_SECRET:=}"
: "${WIKI_ECON_ADMIN_OIDC_SCOPES:=openid email profile}"
: "${WIKI_ECON_ADMIN_ALLOWED_EMAILS:=}"
: "${WIKI_ECON_ADMIN_SESSION_SECRET:=}"
: "${WIKI_ECON_ADMIN_SECURE_COOKIES:=1}"
: "${WIKI_ECON_ADMIN_REQUIRE_VERIFIED_EMAIL:=1}"
: "${WIKI_ECON_ADMIN_API_BASE:=/admin-api}"
: "${WIKI_ECON_ALLOWED_ORIGINS:=}"

if [ "$WIKI_ECON_ENV" = "production" ] && [ "$WIKI_ECON_ADMIN_ENABLED" = "1" ] && [ "$WIKI_ECON_ADMIN_AUTH_MODE" != "oidc" ]; then
  echo "Production admin deployments must use WIKI_ECON_ADMIN_AUTH_MODE=oidc." >&2
  exit 1
fi

if [ "$WIKI_ECON_ADMIN_ENABLED" = "1" ] && [ "$WIKI_ECON_ADMIN_AUTH_MODE" = "oidc" ]; then
  missing=()
  [ -n "$WIKI_ECON_ADMIN_OIDC_ISSUER" ] || missing+=("WIKI_ECON_ADMIN_OIDC_ISSUER")
  [ -n "$WIKI_ECON_ADMIN_OIDC_CLIENT_ID" ] || missing+=("WIKI_ECON_ADMIN_OIDC_CLIENT_ID")
  [ -n "$WIKI_ECON_ADMIN_OIDC_CLIENT_SECRET" ] || missing+=("WIKI_ECON_ADMIN_OIDC_CLIENT_SECRET")
  [ -n "$WIKI_ECON_ADMIN_ALLOWED_EMAILS" ] || missing+=("WIKI_ECON_ADMIN_ALLOWED_EMAILS")
  [ "${#WIKI_ECON_ADMIN_SESSION_SECRET}" -ge 32 ] || missing+=("WIKI_ECON_ADMIN_SESSION_SECRET (32+ chars)")
  if [ "${#missing[@]}" -gt 0 ]; then
    printf 'Missing required admin auth settings: %s\n' "${missing[*]}" >&2
    exit 1
  fi
fi

write_var() {
  local name="$1"
  local value="$2"
  printf '%s=%q\n' "$name" "$value" >>"$tmp_path"
}

mkdir -p "$output_dir"
umask 077
tmp_path="$(mktemp "$output_dir/.wiki-economics.env.XXXXXX")"

printf '# Generated by deploy/cloud-vps/render-env.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >"$tmp_path"
printf '# Safe to commit? No. Keep this file on the VPS only.\n' >>"$tmp_path"

write_var WIKI_ECON_ENV "$WIKI_ECON_ENV"
write_var WIKI_ECON_REPO_URL "$WIKI_ECON_REPO_URL"
write_var WIKI_ECON_REPO_REF "$WIKI_ECON_REPO_REF"
write_var WIKI_ECON_APP_ROOT "$WIKI_ECON_APP_ROOT"
write_var WIKI_ECON_APP_RELEASES "$WIKI_ECON_APP_RELEASES"
write_var WIKI_ECON_APP_CURRENT "$WIKI_ECON_APP_CURRENT"
write_var WIKI_ECON_DATA_DIR "$WIKI_ECON_DATA_DIR"
write_var WIKI_ECON_OUTPUT_ROOT "$WIKI_ECON_OUTPUT_ROOT"
write_var WIKI_ECON_OUTPUT_RELEASES "$WIKI_ECON_OUTPUT_RELEASES"
write_var WIKI_ECON_OUTPUT_CURRENT "$WIKI_ECON_OUTPUT_CURRENT"
write_var WIKI_ECON_SITE_ROOT "$WIKI_ECON_SITE_ROOT"
write_var WIKI_ECON_SITE_RELEASES "$WIKI_ECON_SITE_RELEASES"
write_var WIKI_ECON_SITE_CURRENT "$WIKI_ECON_SITE_CURRENT"
write_var WIKI_ECON_SITE_DIST_DIR "$WIKI_ECON_SITE_DIST_DIR"
write_var WIKI_ECON_STATE_ROOT "$WIKI_ECON_STATE_ROOT"
write_var WIKI_ECON_ENABLED_WIKIS_FILE "$WIKI_ECON_ENABLED_WIKIS_FILE"
write_var WIKI_ECON_SERVICE_USER "$WIKI_ECON_SERVICE_USER"
write_var WIKI_ECON_ADMIN_ENABLED "$WIKI_ECON_ADMIN_ENABLED"
write_var WIKI_ECON_ADMIN_AUTH_MODE "$WIKI_ECON_ADMIN_AUTH_MODE"
write_var WIKI_ECON_ADMIN_PORT "$WIKI_ECON_ADMIN_PORT"
write_var WIKI_ECON_ADMIN_PUBLIC_ORIGIN "$WIKI_ECON_ADMIN_PUBLIC_ORIGIN"
write_var WIKI_ECON_ADMIN_OIDC_ISSUER "$WIKI_ECON_ADMIN_OIDC_ISSUER"
write_var WIKI_ECON_ADMIN_OIDC_CLIENT_ID "$WIKI_ECON_ADMIN_OIDC_CLIENT_ID"
write_var WIKI_ECON_ADMIN_OIDC_CLIENT_SECRET "$WIKI_ECON_ADMIN_OIDC_CLIENT_SECRET"
write_var WIKI_ECON_ADMIN_OIDC_SCOPES "$WIKI_ECON_ADMIN_OIDC_SCOPES"
write_var WIKI_ECON_ADMIN_ALLOWED_EMAILS "$WIKI_ECON_ADMIN_ALLOWED_EMAILS"
write_var WIKI_ECON_ADMIN_SESSION_SECRET "$WIKI_ECON_ADMIN_SESSION_SECRET"
write_var WIKI_ECON_ADMIN_SECURE_COOKIES "$WIKI_ECON_ADMIN_SECURE_COOKIES"
write_var WIKI_ECON_ADMIN_REQUIRE_VERIFIED_EMAIL "$WIKI_ECON_ADMIN_REQUIRE_VERIFIED_EMAIL"
write_var WIKI_ECON_ADMIN_API_BASE "$WIKI_ECON_ADMIN_API_BASE"
write_var WIKI_ECON_ALLOWED_ORIGINS "$WIKI_ECON_ALLOWED_ORIGINS"

mv "$tmp_path" "$output_path"
tmp_path=""
chmod 600 "$output_path"

echo "Wrote $output_path"
